# Architect Controller testing
### 200 Ok
GET http://localhost:6969/api/architects HTTP/1.1
Accept: application/json

### 200 Ok
GET http://localhost:6969/api/architects/300 HTTP/1.1
Accept: application/json

### 200 Ok
DELETE http://localhost:6969/api/architects/del/1 HTTP/1.1
Accept: application/json

### 200 Ok
PUT http://localhost:6969/api/architects/1 HTTP/1.1
Content-Type: application/json

{
  "id" : "1",
  "numberOfEmployees" : 6969
}

### 204 No Content
GET http://localhost:6969/api/architects/900 HTTP/1.1
Accept: application/json

### 404 Not Found
GET http://localhost:6969/api/architectss HTTP/1.1
Accept: application/json

### 500 Internal Server Error
GET http://localhost:6969/api/architects/Denmark HTTP/1.1
Accept: application/json




#Building Controller testing
### 200 Ok
GET http://localhost:6969/api/buildings HTTP/1.1
Accept: application/json

### 200 Ok
GET http://localhost:6969/api/buildings/Denmark HTTP/1.1
Accept: application/json

### 200 Ok
DELETE http://localhost:6969/api/buildings/del/1 HTTP/1.1
Accept: application/json

### 204 No Content
GET http://localhost:6969/api/buildings/Hoevenen HTTP/1.1
Accept: application/json

### 204 No Content
GET http://localhost:6969/api/buildings/123 HTTP/1.1
Accept: application/

### 404 Not Found
GET http://localhost:6969/api/buildingss HTTP/1.1
Accept: application/json

