GET http://localhost:6969/api/architects HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/architects/nameCompany?name=Grimm and Parker Architects HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/architects/nameCompany?name=Diamond Schmitt Architects HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/architects/numberEmployees?amount=399 HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/buildings HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/buildings/location?name=Denmark HTTP/1.1
Accept: application/json

#TODO: HTTP request messages for each endpoint and each possible status code of the response (including 400).
                  #Don't forget your HTTP headers!