# Architect Controller testing
### 200 Ok
GET http://localhost:6969/api/architects HTTP/1.1
Accept: application/json

### 200 Ok
GET http://localhost:6969/api/architects/300 HTTP/1.1
Accept: application/json

### 204 No Content
GET http://localhost:6969/api/architects/900 HTTP/1.1
Accept: application/json

### 400 Bad Request (Could not recreate this error)
#GET http://localhost:6969/api/architects/amount?number=300 HTTP/1.1
#Accept: application/json

### 404 Not Found
GET http://localhost:6969/api/architectss HTTP/1.1
Accept: application/json

### 500 Internal Server Error
GET http://localhost:6969/api/architects/Denmark HTTP/1.1
Accept: application/json




#Building Controller testing
###
GET http://localhost:6969/api/buildings HTTP/1.1
Accept: application/json

###
GET http://localhost:6969/api/buildings/location?name=Denmark HTTP/1.1
Accept: application/json
# Code 200

###
GET http://localhost:6969/api/buildings/location?name=Hoevenen HTTP/1.1
Accept: application/json
# Code 404

###
GET http://localhost:6969/api/buildings/location HTTP/1.1
Accept: application/json
# Code 500

#TODO: HTTP request messages for each endpoint and each possible status code of the response (including 400).
                  #Don't forget your HTTP headers!